### ISSUE TITLE
App crashes directly after sign in.

### ISSUE THREAD

**Issue by CodorStelian** [espressif/esp-rainmaker-android#9]
This bug occurs with the latest changes on Github. I mention that my phone is Huawei P40 Pro, Android 10.
Same bug on Oppo K1, Android 10 as well.
This is the error:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.espressif.rainmaker, PID: 11161
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at com.espressif.cloudapi.ApiManager$3.onResponse(ApiManager.java:482)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8387)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)`

Update: it also affects versions 2.2.1 and 2.2.2

**Comment by khushbushah2302** [comment]
@CodorStelian ,
We will check and fix this asap.

**Comment by khushbushah2302** [comment]
Hi @CodorStelian ,
Sorry for late. This issue is resolved in latest app code.

**Comment by CodorStelian** [comment]
I checked and the problem was solved so I will close this issue.
